/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: nimzu (https://sketchfab.com/nimzuk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/foxs-islands-163b68e09fcc47618450150be7785907
Title: Fox's islands
*/

import React, { use, useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei' //render the model
import { useFrame, useThree } from '@react-three/fiber'
//useFrame gives access to the render loop for frame-based updates.
//useThree provides access to the renderer, camera, and viewport.
import { a } from '@react-spring/three';//a is used for animating 3D elements with react-spring.
import islandScence from '../assets/3d/island.glb'//model

function Island({
    isRotating,
    setIsRotating,
    setCurrentStage,
    ...props
}) {
    const islandRef = useRef();//islandRef is a reference to the 3D island group.
    const { gl, viewport } = useThree();//viewport is used to normalize drag speed across screen sizes.
    const { nodes, materials } = useGLTF(islandScence); //useGLTF loads the island model and extracts its geometry (nodes) and materials.

    const lastX = useRef(0);//lastX stores the last X position of mouse/touch during drag.
    const rotationspeed = useRef(0);//rotationspeed keeps track of how fast the island is spinning.
    const dampingFactor = 0.95;//dampingFactor slows down rotation over time for a smoother feel.

    //Activates rotation and records the initial position.
    const handlePointerDown = (event) => {
        event.stopPropagation();
        event.preventDefault();
        setIsRotating(true);

        const clientX = event.touches ? event.touches.clientX : event.clientX;
        lastX.current = clientX;

    }

    //Ends rotation tracking.
    const handlePointerUp = (event) => {
        event.stopPropagation();
        event.preventDefault();
        setIsRotating(false);
    }


    //Updates the island’s Y-axis rotation while dragging.
    //Adjusts speed depending on drag delta and screen size.
    const handlePointerMove = (event) => {
        event.preventDefault();
        event.stopPropagation();

        if (isRotating) {
            const clientX = event.touches ? event.touches[0].clientX : event.clientX;
            const delta = (clientX - lastX.current) / viewport.width;
            islandRef.current.rotation.y += delta * 0.01 * Math.PI;
            lastX.current = clientX;
            rotationspeed.current = delta * 0.01 * Math.PI;
        }
    }


    //Sets initial rotation speed.
    const handleKeyDown = (event) => {
        if (event.key === 'ArrowLeft') {
            if (event.key === 'ArrowLeft')
                if (!isRotating)
                    setIsRotating(true);
            islandRef.current.rotation.y += 0.005 * Math.PI;
            rotationspeed.current = 0.007;
        }
        else if (event.key === 'ArrowRight') {
            if (!isRotating)
                setIsRotating(true);
            islandRef.current.rotation.y -= 0.005 * Math.PI;
            rotationspeed.current = -0.007;
        }
    }


    //Ends rotation when the key is released.
    const handleKeyUp = (event) => {
        if (event.key === 'ArrowLeft' || event.key === 'ArrowRight') {
            setIsRotating(false);
        }
    }


    useEffect(() => {
        const canvas = gl.domElement;
        canvas.addEventListener('pointerdown', handlePointerDown);
        canvas.addEventListener('pointerup', handlePointerUp);
        canvas.addEventListener('pointermove', handlePointerMove);
        window.addEventListener('keydown', handleKeyDown);
        window.addEventListener('keyup', handleKeyUp);
        return () => {
            canvas.removeEventListener('pointerdown', handlePointerDown);
            canvas.removeEventListener('pointerup', handlePointerUp);
            canvas.removeEventListener('pointermove', handlePointerMove);
            window.removeEventListener('keydown', handleKeyDown);
            window.removeEventListener('keyup', handleKeyUp);
        };
    }, [gl, handlePointerDown, handlePointerUp, handlePointerMove])


    useFrame(() => {
        if (!isRotating) {
            rotationspeed.current *= dampingFactor;

            if (Math.abs(rotationspeed.current) < 0.001) {
                rotationspeed.current = 0;
            }

            islandRef.current.rotation.y += rotationspeed.current;
        }
        else {
            const rotation = islandRef.current.rotation.y;
            const normalization = (rotation % (2 * Math.PI) + 2 * Math.PI) % (2 * Math.PI);
            switch (true) {
                case normalization >= 5.45 && normalization <= 5.85:
                    setCurrentStage(1);
                    break;
                case normalization >= 0.85 && normalization <= 1.3:
                    setCurrentStage(3);
                    break;
                case normalization >= 2.4 && normalization <= 2.6:
                    setCurrentStage(2);
                    break;
                case normalization >= 4.25 && normalization <= 4.75:
                    setCurrentStage(1);
                    break;
                default:
                    setCurrentStage(null);
                    break;
            }
        }
    });

    return (
        <a.group ref={islandRef} {...props}>


            <mesh

                geometry={nodes.polySurface944_tree_body_0.geometry}
                material={materials.PaletteMaterial001}
            />
            <mesh

                geometry={nodes.polySurface945_tree1_0.geometry}
                material={materials.PaletteMaterial001}
            />
            <mesh

                geometry={nodes.polySurface946_tree2_0.geometry}
                material={materials.PaletteMaterial001}
            />
            <mesh

                geometry={nodes.polySurface947_tree1_0.geometry}
                material={materials.PaletteMaterial001}
            />
            <mesh

                geometry={nodes.polySurface948_tree_body_0.geometry}
                material={materials.PaletteMaterial001}
            />
            <mesh

                geometry={nodes.polySurface949_tree_body_0.geometry}
                material={materials.PaletteMaterial001}
            />

            <mesh

                geometry={nodes.pCube11_rocks1_0.geometry}
                material={materials.PaletteMaterial001}
            />

        </a.group>
    )
}

export default Island;